name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Lint & Format Tools
        run: pip install flake8 black

      - name: Run flake8 (Lint)
        run: flake8 . --count --max-complexity=10 --max-line-length=88 --statistics

      - name: Check code format with black
        run: black --check .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Images
        run: |
          docker build -t it66070007/web:latest ./web
          docker build -t it66070007/scheduler:latest ./scheduler
          docker build -t it66070007/worker:latest ./worker
          
          docker push it66070007/web:latest
          docker push it66070007/scheduler:latest
          docker push it66070007/worker:latest